cadena = "Parangaricutirimicuaro"

print("Letras minúsculas:")
if cadena.count('a') > 0: print('a :', cadena.count('a'))
if cadena.count('b') > 0: print('b :', cadena.count('b'))
if cadena.count('c') > 0: print('c :', cadena.count('c'))
if cadena.count('d') > 0: print('d :', cadena.count('d'))
if cadena.count('e') > 0: print('e :', cadena.count('e'))
if cadena.count('f') > 0: print('f :', cadena.count('f'))
if cadena.count('g') > 0: print('g :', cadena.count('g'))
if cadena.count('h') > 0: print('h :', cadena.count('h'))
if cadena.count('i') > 0: print('i :', cadena.count('i'))
if cadena.count('j') > 0: print('j :', cadena.count('j'))
if cadena.count('k') > 0: print('k :', cadena.count('k'))
if cadena.count('l') > 0: print('l :', cadena.count('l'))
if cadena.count('m') > 0: print('m :', cadena.count('m'))
if cadena.count('n') > 0: print('n :', cadena.count('n'))
if cadena.count('o') > 0: print('o :', cadena.count('o'))
if cadena.count('p') > 0: print('p :', cadena.count('p'))
if cadena.count('q') > 0: print('q :', cadena.count('q'))
if cadena.count('r') > 0: print('r :', cadena.count('r'))
if cadena.count('s') > 0: print('s :', cadena.count('s'))
if cadena.count('t') > 0: print('t :', cadena.count('t'))
if cadena.count('u') > 0: print('u :', cadena.count('u'))
if cadena.count('v') > 0: print('v :', cadena.count('v'))
if cadena.count('w') > 0: print('w :', cadena.count('w'))
if cadena.count('x') > 0: print('x :', cadena.count('x'))
if cadena.count('y') > 0: print('y :', cadena.count('y'))
if cadena.count('z') > 0: print('z :', cadena.count('z'))

print("\nLetras mayúsculas:")
if cadena.count('A') > 0: print('A :', cadena.count('A'))
if cadena.count('B') > 0: print('B :', cadena.count('B'))
if cadena.count('C') > 0: print('C :', cadena.count('C'))
if cadena.count('D') > 0: print('D :', cadena.count('D'))
if cadena.count('E') > 0: print('E :', cadena.count('E'))
if cadena.count('F') > 0: print('F :', cadena.count('F'))
if cadena.count('G') > 0: print('G :', cadena.count('G'))
if cadena.count('H') > 0: print('H :', cadena.count('H'))
if cadena.count('I') > 0: print('I :', cadena.count('I'))
if cadena.count('J') > 0: print('J :', cadena.count('J'))
if cadena.count('K') > 0: print('K :', cadena.count('K'))
if cadena.count('L') > 0: print('L :', cadena.count('L'))
if cadena.count('M') > 0: print('M :', cadena.count('M'))
if cadena.count('N') > 0: print('N :', cadena.count('N'))
if cadena.count('O') > 0: print('O :', cadena.count('O'))
if cadena.count('P') > 0: print('P :', cadena.count('P'))
if cadena.count('Q') > 0: print('Q :', cadena.count('Q'))
if cadena.count('R') > 0: print('R :', cadena.count('R'))
if cadena.count('S') > 0: print('S :', cadena.count('S'))
if cadena.count('T') > 0: print('T :', cadena.count('T'))
if cadena.count('U') > 0: print('U :', cadena.count('U'))
if cadena.count('V') > 0: print('V :', cadena.count('V'))
if cadena.count('W') > 0: print('W :', cadena.count('W'))
if cadena.count('X') > 0: print('X :', cadena.count('X'))
if cadena.count('Y') > 0: print('Y :', cadena.count('Y'))
if cadena.count('Z') > 0: print('Z :', cadena.count('Z'))